# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duckrow < Formula
  desc "Get your ducks in a row - manage AI agent skills across projects"
  homepage "https://github.com/barysiuk/duckrow"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.1/duckrow_0.2.1_darwin_amd64.tar.gz"
      sha256 "f562172d9db4c62a1d0c17129662dce1e30f8bb02058a895fa7e16ed5f0ed436"

      def install
        bin.install "duckrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.1/duckrow_0.2.1_darwin_arm64.tar.gz"
      sha256 "8fea0837a6ca00128e5ad92cb175f6b059a73824cddf8fe6b1ff2835f12827d6"

      def install
        bin.install "duckrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.1/duckrow_0.2.1_linux_amd64.tar.gz"
      sha256 "f56d51882ecd383d710910d355c185f117f14e69404c54ce572409764b0676c4"
      def install
        bin.install "duckrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.1/duckrow_0.2.1_linux_arm64.tar.gz"
      sha256 "8ca0af04f38ba520b0365b257e11011d764c4d42145a3be2423d33df53e3f7d3"
      def install
        bin.install "duckrow"
      end
    end
  end
end
