# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duckrow < Formula
  desc "Get your ducks in a row - manage AI agent skills across projects"
  homepage "https://github.com/barysiuk/duckrow"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.0/duckrow_0.2.0_darwin_amd64.tar.gz"
      sha256 "81a7cfb9146f4938c7247fe50ec1d1390688c41ec55594fe34015a43a785af31"

      def install
        bin.install "duckrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.0/duckrow_0.2.0_darwin_arm64.tar.gz"
      sha256 "bfc9129b472306d095ee5e1a76be6fd8b28d62e3b35c0159a6b77ef01651d2ab"

      def install
        bin.install "duckrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.0/duckrow_0.2.0_linux_amd64.tar.gz"
      sha256 "8b6c17c6d529097d92cc70a8459e2bf6bcb584d9cdbf16bc76a99a8d6802e6ce"
      def install
        bin.install "duckrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/barysiuk/duckrow/releases/download/v0.2.0/duckrow_0.2.0_linux_arm64.tar.gz"
      sha256 "61d4792ecdef8120b8d9c47e7393c438e7c599ef2affcb80927010ea41a0f828"
      def install
        bin.install "duckrow"
      end
    end
  end
end
